### ISSUE TITLE
DEV: add script to update citation.cff metadata

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#458]
script will need to parse yaml and then update:
* version number
* commit associated with release
* DOI

```yaml
identifiers:
  - type: doi
    value: 10.5281/zenodo.5828090
...
commit: 5d1b5325306699fdaf4caacd92f9bfb864d00649
version: 0.4.1
date-released: '2022-01-07'
```

I guess this could go in `src/scripts`?

and then use in noxfile as part of "release"? As discussed in #440

the only thing stopping us from automating this--by adding it to the noxifle--would be the DOI, that gets created *after* release -- a chicken-and-egg problem

a solution would be to use the "all releases" DOI in the citation.cff file.  
Can't think of any major drawback to that except people will then be more likely to cite the "all-versions" DOI instead of the DOI for the specific version they used :frowning:
